/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    'matrix',
  {
      type: 'category',
      label: '腾讯云',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/tencentcloud',
        },
      ],
    }, {
      type: 'category',
      label: '阿里云',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/aliyun',
        },
      ],
    },{
      type: 'category',
      label: '华为云',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/huaweicloud',
        },
      ],
    }, {
      type: 'category',
      label: 'Amazon Web Services',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/aws',
        },
      ],
    },{
      type: 'category',
      label: 'Google Cloud Platform',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/gcp',
        },
      ],
    },{
      type: 'category',
      label: 'Microsoft Azure',
      items: [
        {
          type: 'autogenerated',
          dirName: 'matrix/azure',
        },
      ],
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
